version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    cooldown:
      default-days: 0
    allow:
      - dependency-name: "external-content/cookie"
    schedule:
      interval: "weekly"
