baseURL: "https://learn.scientific-python.org/"
title: "Learn Scientific Python"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Documentation for the Scientific Python community."
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Learn Scientific Python
    link: /
  hero:
    title: Learn Scientific Python
    image: logo.svg
  navbar:
    - title: Home
      url: https://scientific-python.org/
    - title: Blog
      url: https://blog.scientific-python.org/
    - title: Contributor Guide
      url: /contributors/
    - title: Maintainer Guide
      url: /maintainers/
    - title: Discussion Forum
      url: https://discuss.scientific-python.org/
      is_external: true
  panel:
    tiles:
      - buttonText: Contributor Guide
        url: /contributors/
        text: Learn how to join the Scientific Python community!
      - buttonText: Development Guide
        url: /development/
        text: Learn recommended tools and approaches for developing Scientific Python libraries.
      - buttonText: Maintainer Guide
        url: /maintainers/
        text: Learn how to build, coordinate, and sustain a healthy project.
      - buttonText: Community Guide
        url: /community/
        text: Get familiar with the Scientific Python community.
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://scientific-python.org
        icon: scientific-python
      - link: https://github.com/scientific-python/learn.scientific-python.org
        icon: github
      - link: https://www.youtube.com/c/ScientificPython-org
        icon: youtube
      - link: https://twitter.com/scientific_py
        icon: twitter
      - link: https://facebook.com/scientific.python
        icon: facebook
      - link: https://www.instagram.com/scientific.python/
        icon: instagram
      - link: https://www.tiktok.com/@scientific.python
        icon: tiktok
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord
      - link: https://blog.scientific-python.org/atom.xml
        icon: rss-feed
      - link: https://discuss.scientific-python.org
        icon: discourse

    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Roadmap
            link: /roadmap/
          - text: Code of Conduct
            link: https://scientific-python.org/code_of_conduct/
      column2:
        title: "Maintainers"
        links:
          - text: SPECs
            link: https://scientific-python.org/specs/
          - text: Grants
            link: https://scientific-python.org/grants/
          - text: Calendars
            link: https://scientific-python.org/calendars/
      column3:
        links:
          - text: Press kit
            link: https://scientific-python.org/press-kit/
