[build.environment]
  PYTHON_VERSION = "3.13"

[build]
  base = "/"
  publish = "public"
  command = "pip install mystmd && make html-all"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
  skipPatterns = ['https://fonts.gstatic.com', 'https://fonts.googleapis.com', "https://unpkg.com", "https://cdn.jsdelivr.net", '/build/']
